let goods = [
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
  },
];

export default goods;