let goods = [
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
    id: 1,
    category: "t-shirt",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
    id: 2,
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
    category: "jacket",
    id: 3,
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
    id: 4,
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
    id: 1,
    category: "t-shirt",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
    id: 2,
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
    id: 3,
    category: "jacket",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
    id: 4,
  },
  {
    name: "T-shirt",
    size: "M",
    price: 100,
    color: "white",
    img: "./images/tshirt.jpg",
    id: 1,
    category: "t-shirt",
  },
  {
    name: "Jeans",
    size: "S",
    price: 400,
    color: "grey",
    img: "./images/jeans.jpg",
    id: 2,
  },
  {
    name: "Jacket",
    size: "L",
    price: 250,
    color: "black",
    img: "./images/jacket.jpg",
    id: 3,
    category: "jacket",
  },
  {
    name: "Skirt",
    size: "XS",
    price: 300,
    color: "red",
    img: "./images/skirt.jpg",
    id: 4,
  },
  {
    name: "Y2K Butterfly crop top",
    size: "S",
    price: 350,
    color: "pink",
    img: "./images/Y2K-Butterfly-Crop-Top.jpg",
    id: 5,
    category: "t-shirt",
  },
  {
    name: "Y2K Butterfly crop top",
    size: "S",
    price: 350,
    color: "pink",
    img: "./images/Y2K-Butterfly-Crop-Top.jpg",
    id: 5,
    category: "t-shirt",
  },
  {
    name: "Y2K Butterfly crop top",
    size: "S",
    price: 350,
    color: "pink",
    img: "./images/Y2K-Butterfly-Crop-Top.jpg",
    id: 5,
    category: "t-shirt",
  },
  {
    name: "Y2K Butterfly crop top",
    size: "S",
    price: 350,
    color: "pink",
    img: "./images/Y2K-Butterfly-Crop-Top.jpg",
    id: 5,
    category: "t-shirt",
  },
  {
    name: "Y2K Butterfly crop top",
    size: "S",
    price: 350,
    color: "pink",
    img: "./images/Y2K-Butterfly-Crop-Top.jpg",
    id: 5,
    category: "t-shirt",
  },
  {
    name: "Nike swoosh jacket",
    size: "L",
    price: 450,
    color: "pale",
    img: "./images/nike-swoosh-pale-jacket.jpg",
    id: 6,
    category: "jacket",
  },
  {
    name: "Nike swoosh jacket",
    size: "L",
    price: 450,
    color: "pale",
    img: "./images/nike-swoosh-pale-jacket.jpg",
    id: 6,
    category: "jacket",
  },
  {
    name: "Nike swoosh jacket",
    size: "L",
    price: 450,
    color: "pale",
    img: "./images/nike-swoosh-pale-jacket.jpg",
    id: 6,
    category: "jacket",
  },
  {
    name: "Nike swoosh jacket",
    size: "L",
    price: 450,
    color: "pale",
    img: "./images/nike-swoosh-pale-jacket.jpg",
    id: 6,
    category: "jacket",
  },
  {
    name: "Nike swoosh jacket",
    size: "L",
    price: 450,
    color: "pale",
    img: "./images/nike-swoosh-pale-jacket.jpg",
    id: 6,
    category: "jacket",
  },
];

export default goods;
